server:
  port: 80
spring:
  activemq:
    # mq的地址
    broker-url: tcp://192.168.1.131:61616
    user: admin
    password: admin
  jms:
    ## 发送的模式
    # false=ptop  true=topic
    pub-sub-domain: false
