spring:
  application:
    name: dubbo-registry-nacos-consumer
server:
  port: 8001

demo:
  service:
    version: 1.0.0

nacos:
  host: 192.168.1.131
  port: 8848
  username: nacos
  password: nacos

dubbo:
  registry:
    address: nacos://${nacos.host}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}
