server:
  port: 82

spring:
  application:
    name: order-82
  cloud:
    nacos:
      server-addr: 192.168.1.131:8848
    sentinel:
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.1.131:8848
            data-id: order-sentinel
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow

logging:
  level:
    com.xiao.openfeign.UserFeign.getUser: debug
feign:
  sentinel:
    enabled: true