server:
  port: 81

spring:
  application:
    name: user-81
  cloud:
    nacos:
      server-addr: 192.168.1.131:8848

    sentinel:
      transport:
        dashboard: 192.168.1.131:8080
        #跟控制台交流的端口,随意指定一个未使用的端口即可
        port: 8719
        #客户端的ip，建议配置上
        clientIp: 192.168.1.107
      datasource:
        ds1:
          nacos:
            server-addr: 192.168.1.131:8848
            data-id: user-sentinel
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow
