
flowable:
  #关闭定时任务JOB
  async-executor-activate: false
  #将databaseSchemaUpdate设置为false。当Flowable发现库与数据库表结构不一致时，不会自动将数据库表结构升级至新版本。
  database-schema-update: true


spring:
  datasource:
#    username: root
#    password: 123456
#    url: jdbc:h2:database/h2db
     url: jdbc:h2:mem:/h2db

