## test1 database
spring:
  datasource:
    test1:
      url: jdbc:h2:database/h2db1
      username: sa
      password: 123456
      driver-class-name: org.h2.Driver
## test2 database
    test2:
      url: jdbc:h2:database/h2db2
      username: sa
      password: 123456
      driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.134:3306/my_test?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456


logging:
  level:
    com.xiao: debug